#!/usr/bin/env python3

import sys, os, re, platform
from os.path import join, dirname, abspath, basename
import unittest
from decimal import Decimal
from datetime import date, time, datetime, timedelta
# from testutils import *
from argparse import ArgumentParser, ArgumentTypeError
import asyncio

def add_to_path():
    """
    Prepends the build directory to the path so that newly built pglib libraries are used, allowing it to be tested
    without installing it.
    """
    # Put the build directory into the Python path so we pick up the version we just built.
    #
    # To make this cross platform, we'll search the directories until we find the .pyd file.

    import imp

    library_exts  = [ t[0] for t in imp.get_suffixes() if t[-1] == imp.C_EXTENSION ]
    library_names = [ '_pglib%s' % ext for ext in library_exts ]

    # Only go into directories that match our version number.

    dir_suffix = '-%s.%s' % (sys.version_info[0], sys.version_info[1])

    build = join(dirname(abspath(__file__)), 'build')

    for root, dirs, files in os.walk(build):
        for d in dirs[:]:
            if not d.endswith(dir_suffix):
                dirs.remove(d)

        for name in library_names:
            if name in files:
                sys.path.insert(0, root)
                return

    sys.exit('Did not find the pglib library in the build directory.')

add_to_path()

import pglib

_TESTSTR = '0123456789-abcdefghijklmnopqrstuvwxyz-'



def _generate_test_string(length):
    """
    Returns a string of composed of `seed` to make a string `length` characters long.

    To enhance performance, there are 3 ways data is read, based on the length of the value, so most data types are
    tested with 3 lengths.  This function helps us generate the test data.

    We use a recognizable data set instead of a single character to make it less likely that "overlap" errors will
    be hidden and to help us manually identify where a break occurs.
    """
    if length <= len(_TESTSTR):
        return _TESTSTR[:length]

    c = (length + len(_TESTSTR)-1) // len(_TESTSTR)
    v = _TESTSTR * c
    return v[:length]


class PGTestCase(unittest.TestCase):

    # These are from the C++ code.  Keep them up to date.

    # # If we are reading a binary, string, or unicode value and do not know how large it is, we'll try reading 2K into a
    # # buffer on the stack.  We then copy into a new Python object.
    # SMALL_READ  = 2048
    #
    # # A read guaranteed not to fit in the MAX_STACK_STACK stack buffer, but small enough to be used for varchar (4K max).
    # LARGE_READ = 4000

    STR_FENCEPOST_SIZES = [ 0, 1, 255, 256, 510, 511, 512, 1023, 1024, 2047, 2048, 4000, 4095, 4096, 4097, 10 * 1024, 20 * 1024 ]

    STR_FENCEPOSTS = [ _generate_test_string(size) for size in STR_FENCEPOST_SIZES ]

    def __init__(self, args, conninfo, method_name):
        unittest.TestCase.__init__(self, method_name)
        self.cnxn = None
        self.args = args
        self.conninfo = conninfo

        self.async = None
        # If set to True, only test async.  If False, only test non-async.
        # Otherwise test both.

    def setUp(self):
        if self.cnxn and self.args.reset:
            self.cnxn.reset()
        else:
            self.cnxn = pglib.connect(self.conninfo)

            if self.args.trace:
                self.cnxn.trace(self.args.trace)

        for i in range(3):
            try:
                self.cnxn.execute("drop table t%d" % i)
            except:
                pass


    def tearDown(self):

        if not self.args.reset:
            try:
                self.cnxn = None
            except:
                # If we've already closed the cursor or connection, exceptions are thrown.
                pass


    def _test_strtype(self, sqltype, value, resulttype=None, colsize=None):
        assert colsize is None or isinstance(colsize, int), colsize
        assert colsize is None or (value is None or colsize >= len(value))

        if colsize:
            sql = "create table t1(s %s(%s))" % (sqltype, colsize)
        else:
            sql = "create table t1(s %s)" % sqltype

        if resulttype is None:
            resulttype = type(value)

        self.cnxn.execute(sql)
        self.cnxn.execute("insert into t1 values($1)", value)
        v = self.cnxn.scalar("select * from t1")
        self.assertEqual(type(v), resulttype)

        if value is not None:
            self.assertEqual(len(v), len(value))

        # To allow buffer --> db --> bytearray tests, always convert the input to the expected result type before
        # comparing.
        if type(value) is not resulttype:
            value = resulttype(value)

        self.assertEqual(v, value)

    def _test_type(self, type, values, round_to=None):
        """
        A generic function for testing inserting and selecting a single data type in
        both synchronous and asynchronous modes.

        type: The data type, such as "boolean".

        values: Either a single value or a list of values to insert and select.
            A column is created or each value.
        """
        if not isinstance(values, (tuple, list)):
            values = [ values ]

        cols = [ chr(ord('a') + i) for i in range(len(values)) ]

        create = "create table t1({})".format(','.join('%s %s' % (col, type) for col in cols))
        insert = "insert into t1 values ({})".format(','.join('$%s' % i for i in range(1, len(values)+1)))
        select = "select {} from t1".format(','.join(cols))

        @asyncio.coroutine
        def _t():
            c = yield from pglib.connect_async(self.conninfo)
            yield from c.execute(create)
            yield from c.execute(insert, *values)
            rset = yield from c.execute(select)
            row = rset[0]
            for (expected, value) in zip(values, row):
                if round_to:
                    value = round(value, round_to)
                self.assertEqual(value, expected)

        if self.async in (None, True):
            loop = asyncio.get_event_loop()
            loop.run_until_complete(_t())

        if self.async in (None, False):
            if self.async is None:
                self.tearDown()
                self.setUp()

            self.cnxn.execute(create)
            self.cnxn.execute(insert, *values)
            rset = self.cnxn.execute(select)
            row = rset[0]
            for (expected, value) in zip(values, row):
                if round_to:
                    value = round(value, round_to)
                self.assertEqual(value, expected)


    def test_execute_ddl(self):
        """
        Ensure we can execute a DDL command and that it returns None.
        """
        r = self.cnxn.execute("create table t1(a int, b int)")
        self.assertEqual(r, None)

    def test_iter(self):
        self.cnxn.execute("create table t1(a varchar(20))")
        self.cnxn.execute("insert into t1 values ('abc')")
        rset = self.cnxn.execute("select * from t1")
        for row in rset:
            self.assertEqual(row.a, 'abc')
            self.assertEqual(row[0], 'abc')

    def test_iter_twice(self):
        "Ensure results can be iterated over multiple times"
        self.cnxn.execute("create table t1(a varchar(20))")
        self.cnxn.execute("insert into t1 values ('abc')")
        rset = self.cnxn.execute("select * from t1")
        for row in rset:
            self.assertEqual(row.a, 'abc')
            self.assertEqual(row[0], 'abc')
        count = 0
        for row in rset:
            count += 1
        self.assertEqual(count, 1)

    def test_version(self):
        self.assertEquals(3, len(pglib.version.split('.'))) # 1.3.1 etc.

    def test_script(self):
        """
        Ensure a script (multiple statements) can be executed.
        """
        sql = """
        select 1;
        select 2;
        select 3;
        """
        self.cnxn.script(sql)

    #
    # copy
    #

    def test_copy_csv(self):
        self.cnxn.execute("create table t1(a int, b varchar(20))")
        self.cnxn.copy_from_csv("t1", open('test-noheader.csv'))
        self.assertEqual(2, self.cnxn.scalar("select count(*) from t1"))
        row = self.cnxn.row("select a,b from t1 where a=2")
        self.assertEqual(row.a, 2)
        self.assertEqual(row.b, 'two')

    def test_copy_csv_header(self):
        self.cnxn.execute("create table t1(a int, b varchar(20))")
        self.cnxn.copy_from_csv("t1", open('test-header.csv'), header=True)
        self.assertEqual(2, self.cnxn.scalar("select count(*) from t1"))
        row = self.cnxn.row("select a,b from t1 where a=2")
        self.assertEqual(row.a, 2)
        self.assertEqual(row.b, 'two')

    def test_copy_csv_gzip(self):
        import gzip
        self.cnxn.execute("create table t1(a int, b varchar(20))")
        self.cnxn.copy_from_csv("t1", gzip.open('test-header.csv.gz'), header=True)
        self.assertEqual(2, self.cnxn.scalar("select count(*) from t1"))
        row = self.cnxn.row("select a,b from t1 where a=2")
        self.assertEqual(row.a, 2)
        self.assertEqual(row.b, 'two')

    def test_copy_csv_string(self):
        self.cnxn.execute("create table t1(a int, b varchar(20))")
        self.cnxn.copy_from_csv("t1", '1,"one"\n2,"two"')
        row = self.cnxn.row("select a,b from t1 where a=2")
        self.assertEqual(row.a, 2)
        self.assertEqual(row.b, 'two')

    def test_copy_csv_string_cols(self):
        self.cnxn.execute("create table t1(a int, b varchar(20))")
        self.cnxn.copy_from_csv("t1(b, a)", '"one",1\n"two",2') # reverse order of cols
        row = self.cnxn.row("select a,b from t1 where a=2")
        self.assertEqual(row.a, 2)
        self.assertEqual(row.b, 'two')

    #
    # row
    #

    def test_row_zero(self):
        self.cnxn.execute("create table t1(a int)")
        value = self.cnxn.row("select a from t1")
        self.assertEqual(value, None)

    def test_row_one(self):
        self.cnxn.execute("create table t1(a int)")
        self.cnxn.execute("insert into t1 values (2)")
        value = self.cnxn.row("select a from t1")
        self.assertEqual(value[0], 2)

    def test_row_many(self):
        self.cnxn.execute("create table t1(a int)")
        self.cnxn.execute("insert into t1 values (1), (2)")
        with self.assertRaises(pglib.Error):
            value = self.cnxn.row("select a from t1")

    #
    # resultset
    #

    def test_rset_length(self):
        """
        Ensure the len(ResultSet) returns the number of rows.
        """
        self.cnxn.execute("create table t1(i int)")
        count = 4
        for i in range(count):
            self.cnxn.execute("insert into t1 values ($1)", i)
        rset = self.cnxn.execute("select * from t1")
        self.assertEquals(len(rset), 4)

    def test_rset_index(self):
        """
        Ensure we can indexing into the ResultSet returns a Row.
        """
        self.cnxn.execute("create table t1(i int)")
        count = 4
        for i in range(count):
            self.cnxn.execute("insert into t1 values ($1)", i)
        rset = self.cnxn.execute("select * from t1")
        row = rset[2]
        self.assertEquals(row[0], 2)

    def test_rset_nonzero(self):
        """
        Ensure a resultset with no rows is "falsey".
        """
        self.cnxn.execute("create table t1(i int)")
        rset = self.cnxn.execute("select * from t1")
        self.assertIsNotNone(rset)
        self.assertFalse(rset)

        self.cnxn.execute("insert into t1 values (1), (2)")
        rset = self.cnxn.execute("select * from t1")
        self.assertIsNotNone(rset)
        self.assertTrue(rset)

    #
    # scalar
    #

    def test_scalar_zero(self):
        """
        Ensure cnxn.scalar() returns None if no rows are selected.
        """
        self.cnxn.execute("create table t1(a int)")
        value = self.cnxn.scalar("select a from t1")
        self.assertEqual(value, None)

    def test_scalar_one(self):
        """
        Ensure cnxn.scalar() returns the first column if one row is selected.
        """
        self.cnxn.execute("create table t1(a int)")
        self.cnxn.execute("insert into t1 values (1)")
        value = self.cnxn.scalar("select a from t1")
        self.assertEqual(value, 1)

    def test_scalar_many(self):
        """
        Ensure cnxn.scalar() raises an exception if multiple rows are selected.
        """
        self.cnxn.execute("create table t1(a int)")
        self.cnxn.execute("insert into t1 values (1), (2)")
        with self.assertRaises(pglib.Error):
            value = self.cnxn.scalar("select a from t1")

    #
    # tuple
    #

    def test_row_to_tuple(self):
        self.cnxn.execute("create table t1(a varchar(20), b int)")
        self.cnxn.execute("insert into t1 values ('one', 1)")
        rset = self.cnxn.execute("select a,b from t1")
        for row in rset:
            t = tuple(row)
            self.assertEqual(t, ('one', 1))

    #
    # boolean
    #

    def test_boolean(self):
        self._test_type('boolean', [True, False])

    #
    # numeric
    #

    def test_smallint(self):
        self._test_type('smallint', [-32768, -2, -1, 0, 1, 2, 32767])

    def test_integer(self):
        self._test_type('integer', [-2147483648, -32768, -2, -1, 0, 1, 2, 32767, 2147483647])

    def test_bigint(self):
        self._test_type('bigint',
                        [-9223372036854775808, -2147483648, -32768, -2, -1, 0,
                         1, 2, 32767, 2147483647, 9223372036854775807])

    def test_float4(self):
        # Careful.  Python doesn't have a float4 datatype, so an float8 is returned.  Unfortunately this means values
        # won't always match even though they "look" like they do when you print them.
        self._test_type('float4', [1.2, -3.4], round_to=2)

    def test_float8(self):
        self._test_type('float8', [1.2, -3.4])

    def test_decimal(self):
        values = [Decimal(s) for s in ['-3.0000000', '123456.7890']]
        self._test_type('decimal(100,7)', values)

    def test_money(self):
        values = [Decimal(s) for s in ['1.23', '0.0', '123.45', '-12.34']]
        self._test_type('money', values)

    # Decimal objects are constructed by first making a string, which we make in
    # English ("12.34").  Make sure that changing the locale to one that uses
    # "," doesn't trip us up.  (I'm not sure why it doesn't.  Ideally we should
    # work on using a different constructor.)  You'll notice that Decimal still
    # parses the values we pass as strings before we even get to pglib.

    def test_decimal_german(self):
        import locale
        locale.setlocale(locale.LC_ALL, 'de_DE')
        values = [Decimal(s) for s in ['-3.0000000', '123456.7890']]
        self._test_type('decimal(100,7)', values)

    def test_money_german(self):
        import locale
        locale.setlocale(locale.LC_ALL, 'de_DE')
        values = [Decimal(s) for s in ['1.23', '0.0', '123.45', '-12.34']]
        self._test_type('money', values)


    def test_decimal_nan(self):
        dec = Decimal('NaN')
        self.cnxn.execute("create table t1(a decimal(100,7))")
        self.cnxn.execute("insert into t1 values($1)", dec)
        result = self.cnxn.scalar("select a from t1")
        self.assertEqual(type(result), Decimal)
        self.assert_(result.is_nan())

    def test_serial(self):
        self.cnxn.execute("create table t1(a serial, b varchar(20))")
        self.cnxn.execute("insert into t1(b) values ('one')")
        self.cnxn.execute("insert into t1(a, b) values (2147483647, 'max')")
        for value in [1, 2147483647]:
            result = self.cnxn.scalar("select a from t1 where a=$1", value)
            self.assertEqual(result, value)

    #
    # varchar
    #

    def test_varchar_null(self):
        self._test_strtype('varchar', None, colsize=100)

    # Generate a test for each fencepost size: test_varchar_0, etc.
    def _maketest(value):
        def t(self):
            self._test_strtype('varchar', value, colsize=len(value))
        return t
    for value in STR_FENCEPOSTS:
        locals()['test_varchar_%s' % len(value)] = _maketest(value)

    #
    # char
    #

    def test_varchar_null(self):
        self._test_strtype('char', None, colsize=100)

    # Generate a test for each fencepost size: test_char_1, etc.
    #
    # Note: There is no test_char_0 since they are blank padded.
    def _maketest(value):
        def t(self):
            self._test_strtype('char', value, colsize=len(value))
        return t
    for value in [v for v in STR_FENCEPOSTS if len(v) > 0]:
        locals()['test_char_%s' % len(value)] = _maketest(value)

    #
    # bytea / bytearray
    #

    def test_bytea(self):
        # Add a NULL byte in the middle to ensure strcpy isn't being used.
        value = b'\xde\xad\x00\xbe\xef'
        self.cnxn.execute("create table t1(a bytea)")
        self.cnxn.execute("insert into t1 values ($1)", value)
        result = self.cnxn.scalar("select * from t1")
        self.assertEqual(value, result)

    # def test_bytea_wrongtype(self):
    #     # Add a NULL byte in the middle to ensure strcpy isn't being used.
    #     value = (b'\x80\x03cmtech.cornerstone.sessions\nSession\nq\x00)\x81q\x01}q\x02(X\x07\x00\x00\x00user_idq\x03NX\t\x00\x00\x00user_nameq\x04NX\x0b\x00\x00\x00permissionsq\x05cbuiltins\nset\nq\x06]q\x07\x85q\x08Rq\tub.',)
    #     self.cnxn.execute("create table t1(a bytea)")
    #     self.cnxn.execute("insert into t1 values ($1)", value)
    #     result = self.cnxn.scalar("select * from t1")
    #     self.assertEqual(value, result)


    #
    # date / timestamp
    #

    def test_date(self):
        self._test_type('date', date(2001, 2, 3))

    def test_time(self):
        value = time(12, 34, 56)
        self.cnxn.execute("create table t1(a time)")
        self.cnxn.execute("insert into t1 values ($1)", value)
        result = self.cnxn.scalar("select a from t1")
        self.assertEqual(result, value)

    def test_timestamp(self):
        self.cnxn.execute("create table t1(a timestamp)")
        value = datetime(2001, 2, 3, 4, 5, 6, 7)
        self.cnxn.execute("insert into t1 values ($1)", value)
        result = self.cnxn.scalar("select a from t1")
        self.assertEqual(result, value)

    def test_interval(self):
        self.cnxn.execute("create table t1(a interval)")
        value = timedelta(days=3, hours=4, minutes=5, seconds=6)
        self.cnxn.execute("insert into t1 values ($1)", value)
        result = self.cnxn.scalar("select a from t1")
        self.assertEqual(result, value)


    #
    # Error Handling
    #

    # def test_error_param_count(self):
    #     """
    #     Was seeing a segfault on OS/X when performing an update with 3 parameters
    #     but supplying only 2 values.  There doesn't seem to be a way to determine this.
    #     """
    #     self.cnxn.execute("create table t1(a varchar(20), b varchar(20), c text)")
    #     self.cnxn.execute("insert into t1(a) values ('1')")
    #     with self.assertRaises(pglib.Error):
    #         self.cnxn.execute("update t1 set b=$1, c=$2 where a=$1",
    #                           'xyz',
    #                           # purposely leave out value for 'c'
    #                           '1')

    #
    # array of parameters
    #

    def test_array_int2(self):
        self.cnxn.execute("create table t1(id int, v int[])")
        value = [None, -32768, -2, -1, 0, 1, 2, 32767]
        self.cnxn.execute("insert into t1 values (1, $1)", value)
        result = self.cnxn.scalar("select v from t1")
        self.assertEqual(result, value)

    def test_array_int4(self):
        # Test with a 4-byte value
        self.cnxn.execute("create table t1(id int, v int[])")
        value = [None, -2147483648, -32768, -2, -1, 0, 1, 2, 32767, 2147483647]
        self.cnxn.execute("insert into t1 values (1, $1)", value)
        result = self.cnxn.scalar("select v from t1")
        self.assertEqual(result, value)

    def test_array_int8(self):
        MAX_INTEGER = 2147483647
        self.cnxn.execute("create table t1(id int, v bigint[])")
        value = [None, -9223372036854775808, -2147483648, -32768, -2, -1, 0,
                 1, 2, 32767, 2147483647, 9223372036854775807]
        self.cnxn.execute("insert into t1 values (1, $1)", value)
        result = self.cnxn.scalar("select v from t1")
        self.assertEqual(result, value)

    def test_array_text(self):
        self.cnxn.execute("create table t1(id int, v text[])")
        value = ['one', None, 'two']
        self.cnxn.execute("insert into t1 values (1, $1)", value)
        result = self.cnxn.scalar("select v from t1")
        self.assertEqual(result, value)

    def test_array_int_in(self):
        self.cnxn.execute("create table t1(id int)")
        for value in [1,2,3]:
            self.cnxn.execute("insert into t1 values ($1)", value)
        value = [1,3]
        rset = self.cnxn.execute("select id from t1 where id = ANY($1)", value)
        self.assertEquals(len(rset), 2)

    def test_array_int8_in(self):
        MAX_INTEGER = 2147483647
        self.cnxn.execute("create table t1(id bigint)")
        for value in [1, MAX_INTEGER * 2, sys.maxsize]:
            self.cnxn.execute("insert into t1 values ($1)", value)
        value = [1,sys.maxsize]
        rset = self.cnxn.execute("select id from t1 where id = ANY($1)", value)
        self.assertEquals(len(rset), 2)

    def test_array_text_in(self):
        self.cnxn.execute("create table t1(id int, v text)")
        for value in ['one', 'two', 'three']:
            self.cnxn.execute("insert into t1 values (1, $1)", value)
        value = ['one', 'three']
        rset = self.cnxn.execute("select v from t1 where v = ANY($1)", value)
        self.assertEquals(len(rset), 2)

    # I don't have a good solution for this yet.  If an array is empty or all NULLs, we don't
    # know what type to choose when sending to the DB.  I've chosen text, but it doesn't
    # convert as wells as I'd hoped - the backend won't accept it.  I've tried ANYARRAYOID and
    # that doesn't work either.

    # def test_array_none(self):
    #     # I've made the data type 'int[]' since we're going to try inserting as text[].  All we
    #     # have is "None", so we don't know what type and will default to text.
    #     self.cnxn.execute("create table t1(id int, v int[])")
    #     value = [None, None, None]
    #     self.cnxn.execute("insert into t1 values (1, $1)", value)
    #     result = self.cnxn.scalar("select v from t1")
    #     self.assertEqual(result, value)

    # This looks weird, but each type must be tested like this.  Code in each type ensures the
    # types are the same.  Perhaps we should fix that, but I didn't want to go through the loop
    # so many times.

    def test_array_int_bad(self):
        self.cnxn.execute("create table t1(id int, v int[])")
        value = [1,'two']
        with self.assertRaises(pglib.Error):
            self.cnxn.execute("insert into t1 values (1, $1)", value)

    #
    # Miscellaneous
    #

    def test_insert_result(self):
        """
        Ensure that an insert returns the row count, not a result set.
        """
        self.cnxn.execute("create table t1(a varchar(20), b int)")
        result = self.cnxn.execute("insert into t1 values ('one', 1)")
        self.assertEqual(result, 1)

    def test_repr(self):
        """
        For debugging purposes, printing a row should produce the same output as a tuple.
        """
        self.cnxn.execute("create table t1(a varchar(20), b int)")
        self.cnxn.execute("insert into t1 values ('one', 1)")
        row = self.cnxn.row("select a,b from t1")
        t = ('one', 1)
        self.assertEqual(str(row), str(t))

    def test_cnxn_status(self):
        # I don't know how to make a bad status, so we'll just ensure the attribute exists
        # and is true.
        self.assertTrue(self.cnxn.status)

    def test_txn_status(self):
        self.assertEqual(self.cnxn.transaction_status, pglib.PQTRANS_IDLE)
        self.cnxn.execute("begin")
        self.assertEqual(self.cnxn.transaction_status, pglib.PQTRANS_INTRANS)
        try:
            self.cnxn.execute("drop table bogus")
        except:
            pass
        self.assertEqual(self.cnxn.transaction_status, pglib.PQTRANS_INERROR)

        self.cnxn.execute("rollback")
        self.assertEqual(self.cnxn.transaction_status, pglib.PQTRANS_IDLE)


    def test_uuid(self):
        import uuid
        value = uuid.UUID('4bfe4344-e7f2-41c3-ab88-1aecd79abd12')
        self.cnxn.execute("create table t1(a uuid)")
        self.cnxn.execute("insert into t1 values ($1)", value)
        result = self.cnxn.scalar("select a from t1")
        self.assertEqual(result, value)

    def test_rset_columns(self):
        self.cnxn.execute("create table t1(a int, b int, c int)")
        self.cnxn.execute("insert into t1 values (1,1,1)")
        rset = self.cnxn.execute("select a,b,c from t1")
        self.assertEqual(rset.columns, ('a', 'b', 'c'))

    def test_row_columns(self):
        self.cnxn.execute("create table t1(a int, b int, c int)")
        self.cnxn.execute("insert into t1 values (1,1,1)")
        row = self.cnxn.row("select a,b,c from t1")
        self.assertEqual(row.columns, ('a', 'b', 'c'))

    def test_assignment(self):
        """
        Ensure columns can be assigned to rows.
        """
        self.cnxn.execute("create table t1(a int)")
        self.cnxn.execute("insert into t1 values (1)")
        row = self.cnxn.row("select a from t1")
        self.assertEqual(row.a, 1)
        row.a = 2
        self.assertEqual(row.a, 2)

    def test_row_failure(self):
        """
        Calling cnxn.row() with invalid SQL used to return "SQL wasn't a
        query" because row was not detecting the error before trying to access
        results.
        """
        self.cnxn.execute("create table t1(a varchar(20))")
        try:
            self.cnxn.row("select bogus from t1")
        except pglib.Error as ex:
            msg = str(ex)
            assert '[42703]' in msg

    def test_scalar_failure(self):
        """
        Calling cnxn.scalar() with invalid SQL used to return "SQL wasn't a
        query" because row was not detecting the error before trying to access
        results.
        """
        self.cnxn.execute("create table t1(a varchar(20))")
        try:
            self.cnxn.scalar("select bogus from t1")
        except pglib.Error as ex:
            msg = str(ex)
            assert '[42703]' in msg, "msg={!r}".format(msg)


    def test_null_param(self):
        # At one point, inserting a NULL parameter followed by a non-NULL parameter caused a segfault.
        #
        # A single parameter or two Nones did not crash.

        self.cnxn.execute("create table t1(a varchar(20), b integer)")
        self.cnxn.execute("insert into t1(a) values ($1)", 'testing')
        self.cnxn.execute("update t1 set a=$1, b=$2", None, 1)

    def test_txn_commit(self):
        self.cnxn.execute("create table t1(a int)")
        other = pglib.connect(self.conninfo)
        other.begin()
        other.execute("insert into t1 values (1)")
        other.commit()
        count = self.cnxn.scalar("select count(*) from t1")
        self.assertEqual(count, 1)

    def test_txn_failure(self):
        self.cnxn.execute("create table t1(a int)")
        other = pglib.connect(self.conninfo)
        other.begin()
        other.execute("insert into t1 values (1)")
        other = None # should roll back
        count = self.cnxn.scalar("select count(*) from t1")
        self.assertEqual(count, 0)

    def test_txn_rollback(self):
        self.cnxn.execute("create table t1(a int)")
        other = pglib.connect(self.conninfo)
        other.begin()
        other.execute("insert into t1 values (1)")
        other.rollback()
        count = self.cnxn.scalar("select count(*) from t1")
        self.assertEqual(count, 0)

    def test_tmp(self):
        """
        A sync version of test_async.  We're getting the results in text format
        instead of binary even though I've requested binary.
        """
        self.cnxn.execute("create table t1(a varchar(20), b int)")
        self.cnxn.execute("insert into t1 values ($1, $2)", 'abc', 3)
        rset = self.cnxn.execute("select a, b from t1")
        for row in rset:
            self.assertEqual(row.a, 'abc')
            self.assertEqual(row[0], 'abc')
            self.assertEqual(row.b,  3)
            self.assertEqual(row[1], 3)

    def test_async(self):
        @asyncio.coroutine
        def _t():
            c = yield from pglib.connect_async(self.conninfo)
            yield from c.execute("create table t1(a varchar(20), b int)")
            yield from c.execute("insert into t1 values ('abc', 3)")
            rset = yield from c.execute("select a, b from t1")
            for row in rset:
                self.assertEqual(row.a, 'abc')
                self.assertEqual(row[0], 'abc')
                self.assertEqual(row.b,  3)
                self.assertEqual(row[1], 3)

        loop = asyncio.get_event_loop()
        loop.run_until_complete(_t())

    def test_async_params(self):
        @asyncio.coroutine
        def _t():
            c = yield from pglib.connect_async(self.conninfo)
            yield from c.execute("create table t1(a varchar(20), b int)")
            yield from c.execute("insert into t1(a, b) values ($1, $2)", 'abc', 2)
            rset = yield from c.execute("select a, b from t1")
            for row in rset:
                self.assertEqual(row.a,  'abc')
                self.assertEqual(row[0], 'abc')
                self.assertEqual(row.b,  2)
                self.assertEqual(row[1], 2)

        loop = asyncio.get_event_loop()
        loop.run_until_complete(_t())

    def test_notify(self):
        @asyncio.coroutine
        def _read(queue):
            return (yield from queue.get())

        @asyncio.coroutine
        def _t():
            listener = yield from pglib.connect_async(self.conninfo)
            c = yield from pglib.connect_async(self.conninfo)

            queue = yield from listener.listen('test')

            yield from c.notify('test')
            yield from c.notify('test', "pglib's payload")

            item = yield from asyncio.wait_for(_read(queue), 3.0)
            self.assertIsNotNone(item)

        loop = asyncio.get_event_loop()
        loop.run_until_complete(_t())


def _check_conninfo(value):
    value = value.strip()
    if not re.match(r'^\w+=.+$', value):
        raise ArgumentTypeError('conninfo must be key=value ("{}")'.format(value))
    return value

def main():
    parser = ArgumentParser()
    parser.add_argument('-u', '--user')
    parser.add_argument('-v', '--verbose', action='count', help='Increment verbosity', default=0)
    parser.add_argument('-t', '--test', help='Run only the named test')
    parser.add_argument('--trace')
    parser.add_argument('--reset', action='store_true', default=False, help="Reuse connection for tests")
    parser.add_argument('conninfo', nargs='*', type=_check_conninfo, help='connection string component')

    args = parser.parse_args()

    conninfo = {
        'host'   : 'localhost',
        'dbname' : 'test',
    }

    for part in args.conninfo:
        match = re.match(r'^(\w+)=(.+)$', part)
        conninfo[match.group(1)] = match.group(2)

    conninfo = ' '.join('{}={}'.format(key, value) for (key, value) in conninfo.items())

    if args.verbose:
        print('Version:', pglib.version)
        print('conninfo:', conninfo)

    if args.test:
        # Run a single test
        if not args.test.startswith('test_'):
            args.test = 'test_%s' % (args.test)

        s = unittest.TestSuite([ PGTestCase(args, conninfo, args.test) ])
    else:
        # Run all tests in the class

        methods = [ m for m in dir(PGTestCase) if m.startswith('test_') ]
        methods.sort()
        s = unittest.TestSuite([ PGTestCase(args, conninfo, m) for m in methods ])

    testRunner = unittest.TextTestRunner(verbosity=args.verbose)
    result = testRunner.run(s)



if __name__ == '__main__':

    # Add the build directory to the path so we're testing the latest build, not the installed version.

    main()
